### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sergeydigl3** [HOWZ1T/py_proxy#1]
0 proxies

**Comment by HOWZ1T** [comment]
Hi, could you be more specific ?
If you are filtering proxies by country, try another country or remove the filter.

**Comment by HOWZ1T** [comment]
After some further investigation, it appears that their is an issue with getting the proxies.
I will look into resolving this issue.

**Comment by HOWZ1T** [comment]
The issue is resolved.
