### ISSUE TITLE
ModuleNotFoundError: No module named 'proxy'

### ISSUE THREAD

**Issue by berkai** [HOWZ1T/py_proxy#7]
when I install the package correctly I cant call the library with the "from proxy import Proxy" code.

python: 3.6.8

**Comment by HOWZ1T** [comment]
Hi,

Thanks for reporting the issue !

This problem has been resolved in the new 0.2.6 release :)
To install it please use:
>pip install py_proxy==0.2.6

All the best,
HOWZ1T
